version: 0.2

phases:
  pre_build:
    commands:
      - echo Entered the pre_build phase...
      - echo Restoring NuGet packages...
      - dotnet restore
  build:
    commands:
      - echo Entered the build phase...
      - echo Building the application...
      - dotnet build
      - echo Publishing the application...
      - dotnet publish -c Release
  post_build:
    commands:
      - echo Entered the post_build phase...
      - echo Zipping the published artifacts...
      - cd <YOUR_PROJECT_DIRECTORY>/bin/Release/netcoreapp3.1/publish
      - zip -r myapp.zip *
      - echo Uploading the application to S3...
      - aws s3 cp myapp.zip s3://<YOUR_S3_BUCKET_NAME>/myapp.zip
artifacts:
  files:
    - myapp.zip
  discard-paths: yes
