version: 0.2
phases:
  install:
    runtime-versions:
      dotnet: 7.0
  pre_build:
    commands:
      - dotnet restore PrescriptionGeneration/PrescriptionGeneration.csproj
  build:
    commands:
      - dotnet build PrescriptionGeneration/PrescriptionGeneration.csproj
  post_build:
    commands:
      - dotnet publish -c Release -o ./app/ PrescriptionGeneration/PrescriptionGeneration.csproj
artifacts:
  files:
    - '**/*'