version: 0.2
env:
    variables:
        PROJECT: PrescriptionGeneration
        DOTNET_CORE_RUNTIME: 7.0

phases:
  install:
    runtime-versions:
      dotnet: ${DOTNET_CORE_RUNTIME}
  pre_build:
    commands:
      - dotnet restore 
  build:
    commands:
      - dotnet build -c Release
  post_build:
    commands:
      - dotnet publish -c Release -r linux-x64 -o ./build_output  ./${PROJECT}/${PROJECT}.csproj --self-contained false
      - cp Procfile ./build_output
artifacts:
  files:
    - '**/*'
  base-directory: ./build_output
  discard-paths: no