version: 0.2
env:
    variables:
        PROJECT: PrescriptionGeneration
        DOTNET_CORE_RUNTIME: 6.0

phases:
  install:
    runtime-versions:
      dotnet: ${DOTNET_CORE_RUNTIME}
  pre_build:
    commands:
      - dotnet restore ${PROJECT}/${PROJECT}.csproj
  build:
    commands:
      - dotnet build ${PROJECT}/${PROJECT}.csproj
  post_build:
    commands:
      - dotnet publish -c Release -o ./app ${PROJECT}/${PROJECT}.csproj


artifacts:
  files:
    - '**/*'
